[package]
name = "sk"
version = "0.1.0"
edition = "2021"

[dependencies]
calamine = "=0.18.0"
sqlx = { version = "=0.5.13", features = [ "runtime-tokio-rustls", "postgres" ] }
serde = { version = "=1.0", features = ["derive"] }
tokio = { version = "=1.18.0", features = ["full"] }
